<?php

namespace Dimitriytiho\DevopsHealth\Collections;

use Illuminate\Support\Collection;

class ResultCollection extends Collection
{

    // push проверить что это объект \Spatie\Health\Checks\Result)
    public function push(...$values)
    {
        $new = [];
        foreach ($values as $value) {
            if (!$value instanceof \Spatie\Health\Checks\Result) {
                throw new \Exception('The result should be an instance of '.\Spatie\Health\Checks\Result::class);
            }

            $meta = $value->meta;
            $status = $value->status->value;
            $check = $value->check->getName();
            $label = $value->check->getLabel();
            $message = $value->getNotificationMessage();
            $shortSummary = $value->getShortSummary();
            $ended_at = $value->ended_at->toDateTimeString();
            $new = [
                'check' => $check,
                'label' => $label,
                'status' => $status,
                'message' => $message,
                'shortSummary' => $shortSummary,
                'ended_at' => $ended_at,
                'meta' => $meta,
            ];
        }

        return parent::push($new); // TODO: Change the autogenerated stub
    }

}
